spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/null_713_3565/config-repo.git
          skip-ssl-validation: true
          timeout: 5
server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka